# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 20:20
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqindex',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('category', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('questions', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('question', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('answer', wagtail.wagtailcore.blocks.CharBlock(required=True))), template='blocks/faq/question.html')))), template='blocks/faq/category.html')),), blank=True, null=True),
        ),
    ]
