# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:48
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedwork',
            name='body',
        ),
        migrations.AddField(
            model_name='publishedwork',
            name='chapters',
            field=wagtail.wagtailcore.fields.StreamField((('chapter', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('text', wagtail.wagtailcore.blocks.RichTextBlock(required=True))))),), default=[]),
            preserve_default=False,
        ),
    ]
