# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_auto_20171016_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedwork',
            name='summary',
            field=models.TextField(blank=True, help_text="This is shown at the top of the published work's own page and in search results.", null=True),
        ),
    ]
