# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_auto_20171016_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedwork',
            name='generate_navigation',
            field=models.BooleanField(default=True, help_text='This determines whether a navigation menu for chapters will be generated for this page', verbose_name='Generate a navigation menu'),
        ),
    ]
