# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('publish', '0004_publishedwork_generate_navigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedWorkTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='publish.PublishedWork')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_publishedworktag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='publishedwork',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='publish.PublishedWorkTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
