# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_auto_20171017_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongStory',
            fields=[
                ('publishedwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publish.PublishedWork')),
                ('body', wagtail.wagtailcore.fields.StreamField((('chapter', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('text', wagtail.wagtailcore.blocks.RichTextBlock(required=True))))),))),
                ('generate_navigation', models.BooleanField(default=True, help_text='This determines whether a navigation menu for chapters will be generated for this page', verbose_name='Generate a navigation menu')),
            ],
            options={
                'abstract': False,
            },
            bases=('publish.publishedwork',),
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('publishedwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publish.PublishedWork')),
                ('body', wagtail.wagtailcore.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('publish.publishedwork',),
        ),
        migrations.CreateModel(
            name='ShortStory',
            fields=[
                ('publishedwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publish.PublishedWork')),
                ('body', wagtail.wagtailcore.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('publish.publishedwork',),
        ),
        migrations.RemoveField(
            model_name='publishedwork',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='publishedwork',
            name='generate_navigation',
        ),
    ]
