# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 20:09
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='navigation',
            field=wagtail.wagtailcore.fields.StreamField((('item', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(max_length=16, min_length=2, required=True)), ('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=True))), template='blocks/navigation_item.html')),), blank=True, help_text='The list of navigation items', null=True),
        ),
    ]
